import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const sectionRef = useRef(null);

  useEffect(() => {
    const unlisten = () => {
      // Scroll to the section and center it when the location changes
      if (sectionRef.current) {
        debug;
        console.log("section =>", sectionRef.current);
        sectionRef.current.scrollIntoView({
          behavior: "smooth",
          block: "center",
        });
      }
    };

    window.addEventListener("popstate", unlisten);

    return () => {
      window.removeEventListener("popstate", unlisten);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/contacts" className={styles.card}>
            <h2>CONTACT MANAGER&rarr;</h2>
          </a>

          <a href="/json-to-html" className={styles.card}>
            <h2>JSON TO HTML &rarr;</h2>
          </a>
          <a href="/tic-tac-toe" className={styles.card}>
            <h2>TIC-TAC-TOE &rarr;</h2>
          </a>
          {/* {[1, 2, 3, 4, 5].map((ele) => (
            <a
              key={ele}
              href={`/contacts/${ele}`}
              className={styles.card}
              ref={sectionRef}
            >
              <h2>Contact to {ele} &rarr;</h2>
            </a>
          ))} */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
